runtime: go120

instance_class: F2

main: ./cmd/websocket-server

automatic_scaling:
  max_instances: 1
  min_instances: 1

handlers:
- url: /server
  script: auto
  secure: always
- url: /client
  script: auto
  secure: always