runtime: go
runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "1.20"
network:
  forwarded_ports: 
    - 8081/tcp
resources:
  cpu: 2
  memory_gb: 1
  disk_size_gb: 10
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1